export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  profile: "/profile",
  gapAnalysis: "/gap-analysis",
  roadmap: "/roadmap",
  projects: "/projects",
  courses: "/courses",
  interview: "/interview",
  resume: "/resume",
  analytics: "/analytics",
  notifications: "/notifications",
  jobs: "/jobs",
  admin: "/admin",
} as const;
