import { motion } from "framer-motion";
import { ArrowRight, BarChart3, BrainCircuit, Building2, CheckCircle2, GraduationCap, Route, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { api } from "../api";
import { useAuth } from "../auth";
import { ErrorText, roleHome } from "../components";

export function Landing() {
  const {user}=useAuth(); if(user)return <Navigate to={roleHome[user.role]}/>;
  return <div className="min-h-screen bg-white">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link to="/" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><GraduationCap/></span><span className="font-[Manrope] text-xl font-extrabold">SGIP</span></Link><div className="flex gap-2"><Link className="btn-secondary" to="/login">Log in</Link><Link className="btn-primary" to="/register">Get started</Link></div></nav>
    <main><section className="relative overflow-hidden px-5 pb-24 pt-16 md:pt-24"><div className="absolute left-1/2 top-0 -z-0 h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-gradient-to-b from-blue-50 via-indigo-50/60 to-transparent blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
      <motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}><span className="pill mb-5 gap-2 bg-blue-50 text-blue-700"><Sparkles size={13}/> Intelligence for placement readiness</span><h1 className="max-w-3xl text-5xl font-extrabold leading-[1.05] text-slate-950 md:text-7xl">Bridge your skill gap.<span className="block bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">Become placement ready.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Turn your skills, projects, and evidence into an explainable readiness score—and a clear route to the career you want.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="btn-primary px-6 py-3.5">Start your assessment <ArrowRight size={17}/></Link><a href="#how" className="btn-secondary px-6 py-3.5">See how it works</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-500">{["Explainable scoring","Personal roadmaps","Institution analytics"].map(x=><span className="flex items-center gap-2" key={x}><CheckCircle2 className="text-emerald-500" size={16}/>{x}</span>)}</div></motion.div>
      <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{delay:.15}} className="relative"><div className="rounded-[28px] border border-slate-200 bg-white p-4 shadow-[0_30px_80px_rgba(30,64,175,.16)]"><div className="rounded-2xl bg-[#0e1a32] p-6 text-white"><p className="text-xs uppercase tracking-[.16em] text-blue-300">Readiness snapshot</p><div className="mt-6 flex items-end justify-between"><div><p className="text-sm text-slate-400">Target role</p><h3 className="mt-1 text-xl">Full Stack Developer</h3></div><b className="text-5xl">72<span className="text-xl text-blue-300">%</span></b></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-blue-400 to-emerald-400"/></div></div><div className="grid gap-3 p-3 sm:grid-cols-3">{[["8","Skills matched"],["4","Gaps found"],["12","Tasks planned"]].map(([v,l])=><div className="rounded-xl bg-slate-50 p-4" key={l}><b className="text-2xl">{v}</b><p className="text-xs text-slate-500">{l}</p></div>)}</div></div></motion.div>
    </div></section>
    <section className="bg-slate-50 px-5 py-24"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">One connected platform</p><h2 className="mt-2 text-3xl font-bold md:text-4xl">From evidence to employability</h2><p className="mt-3 text-slate-600">Every recommendation connects back to role requirements and student evidence.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[Target,"Gap intelligence","See exactly where current proficiency falls short."],[Route,"Adaptive roadmap","Prioritized phases turn gaps into a weekly action plan."],[BrainCircuit,"Responsible AI","AI explains and suggests; deterministic logic owns scoring."],[BarChart3,"Cohort analytics","Placement teams spot readiness and systemic gaps."]].map(([I,t,d]:any)=><div className="card" key={t}><I className="text-blue-600"/><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
    <section id="how" className="px-5 py-24"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">How it works</p><h2 className="mt-2 text-3xl font-bold">Clarity in three steps</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[["01","Build your evidence profile","Add skills, projects, certifications, assessments, and resume evidence."],["02","Choose your destination","Select a curated career role with transparent proficiency requirements."],["03","Close the right gaps","Follow a personalized roadmap and watch readiness improve over time."]].map(([n,t,d])=><div key={n} className="relative border-l-2 border-blue-100 pl-6"><b className="text-sm text-blue-600">{n}</b><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
    <section className="px-5 pb-20"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 rounded-[28px] bg-[#0d1b35] px-8 py-12 text-white md:flex-row"><div><h2 className="text-3xl font-bold">Ready to make every skill count?</h2><p className="mt-2 text-slate-300">Start building your placement readiness profile today.</p></div><Link to="/register" className="btn bg-white px-6 py-3 text-slate-950 hover:bg-blue-50">Create free account <ArrowRight size={17}/></Link></div></section></main>
    <footer className="border-t px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-slate-500 md:flex-row"><span>© 2026 Skill Gap Intelligence Platform</span><span className="flex gap-5"><a href="/docs">API docs</a><span>Privacy</span><span>Security</span></span></div></footer>
  </div>;
}

export function AuthPage({mode}:{mode:"login"|"register"}) {
  const {user,login}=useAuth(); const nav=useNavigate(); const {register,handleSubmit,formState:{isSubmitting}}=useForm<any>(); const [error,setError]=useState<any>();
  if(user)return <Navigate to={roleHome[user.role]}/>;
  async function submit(data:any){try{setError(null);const res=await api.post(`/auth/${mode}`,data);login(res.data.token,res.data.user);nav(roleHome[res.data.user.role]);}catch(e){setError(e)}}
  return <div className="grid min-h-screen lg:grid-cols-2"><div className="flex items-center justify-center bg-white p-6"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2.5 font-[Manrope] text-xl font-extrabold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><GraduationCap/></span>SGIP</Link><p className="text-sm font-bold uppercase tracking-wider text-blue-600">{mode==="login"?"Welcome back":"Start your journey"}</p><h1 className="mt-2 text-3xl font-bold">{mode==="login"?"Sign in to your account":"Create your SGIP account"}</h1><p className="mt-2 text-sm text-slate-500">{mode==="login"?"Continue building your placement readiness.":"Turn your skills into a career-ready plan."}</p>
    <form className="mt-8 space-y-4" onSubmit={handleSubmit(submit)}>{mode==="register"&&<div><label className="label">Full name</label><input className="input" required {...register("name")} placeholder="Your full name"/></div>}<div><label className="label">Email address</label><input className="input" type="email" required {...register("email")} placeholder="you@college.edu"/></div><div><div className="flex justify-between"><label className="label">Password</label>{mode==="login"&&<span className="text-xs font-semibold text-blue-600">Forgot password?</span>}</div><input className="input" type="password" minLength={8} required {...register("password")} placeholder="Minimum 8 characters"/></div>{mode==="register"&&<div><label className="label">I am a</label><select className="input" {...register("role")} defaultValue="student"><option value="student">Student</option><option value="mentor">Mentor</option><option value="placement">Placement officer</option></select></div>}{error&&<ErrorText error={error}/>}<button disabled={isSubmitting} className="btn-primary w-full py-3">{isSubmitting?"Please wait…":mode==="login"?"Sign in":"Create account"}<ArrowRight size={16}/></button></form><p className="mt-6 text-center text-sm text-slate-500">{mode==="login"?"New to SGIP?":"Already have an account?"} <Link className="font-semibold text-blue-600" to={mode==="login"?"/register":"/login"}>{mode==="login"?"Create an account":"Sign in"}</Link></p>
    {mode==="login"&&<div className="mt-8 rounded-xl bg-slate-50 p-4 text-xs text-slate-500"><b>Demo accounts:</b> student@sgip.local, mentor@sgip.local, placement@sgip.local, admin@sgip.local<br/>Password: Password123!</div>}</div></div>
    <div className="relative hidden overflow-hidden bg-[#0d1b35] p-12 text-white lg:flex lg:items-end"><div className="absolute -right-28 -top-28 h-96 w-96 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative max-w-xl"><ShieldCheck size={42} className="text-blue-400"/><blockquote className="mt-7 text-3xl font-semibold leading-snug">“Readiness becomes actionable when every score has evidence—and every gap has a next step.”</blockquote><div className="mt-8 flex gap-8 text-sm text-slate-300"><span className="flex items-center gap-2"><Building2 size={17}/> Institution ready</span><span className="flex items-center gap-2"><Users size={17}/> Role based</span></div></div></div></div>
}

import { useState } from "react";
