import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, BarChart3, BriefcaseBusiness, CheckCircle2, Download, FileText, Gauge, Search, ShieldCheck, UserCheck, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../api";
import { Empty, Loading, PageHeader, ScoreRing, Stat } from "../components";
const q=(key:string,url:string)=>useQuery({queryKey:[key],queryFn:()=>api.get(url).then(r=>r.data)});

export function MentorDashboard(){
 const {data,isLoading}=q("mentor-students","/mentor/students");if(isLoading)return <Loading/>;const students=data?.students||[],needs=students.filter((s:any)=>(s.latestReport?.readinessScore||0)<60);
 return <><PageHeader eyebrow="Mentor workspace" title="Guide progress that matters" description="Focus support on students with the largest high-priority gaps."/><div className="grid gap-4 md:grid-cols-3"><Stat label="Assigned students" value={students.length} detail="Active mentees" icon={Users}/><Stat label="Needs attention" value={needs.length} detail="Readiness below 60%" icon={Activity} tone="amber"/><Stat label="Placement ready" value={students.filter((s:any)=>s.latestReport?.readinessScore>=75).length} detail="Readiness at or above 75%" icon={UserCheck} tone="emerald"/></div><StudentCards students={students}/></>
}
function StudentCards({students}:{students:any[]}){return <div className="card mt-5"><div className="flex justify-between"><h2 className="text-lg font-bold">Assigned students</h2><Link to="/mentor/students" className="text-sm font-semibold text-blue-600">View all →</Link></div><div className="mt-4 divide-y">{students.length?students.map(s=><Link to={`/mentor/students/${s._id}`} className="flex items-center justify-between py-4 hover:bg-slate-50" key={s._id}><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 font-bold text-indigo-600">{s.name[0]}</div><div><b>{s.name}</b><p className="text-xs text-slate-500">{s.profile?.branch||"Branch not set"} · Year {s.profile?.year||"—"}</p></div></div><div className="text-right"><b className={s.latestReport?.readinessScore>=75?"text-emerald-600":"text-amber-600"}>{s.latestReport?.readinessScore??"—"}{s.latestReport&&"%"}</b><p className="text-xs text-slate-400">readiness</p></div></Link>):<Empty title="No students assigned" text="An administrator can assign students to your mentor account."/>}</div></div>}
export function MentorStudents(){const x=q("mentor-students","/mentor/students");if(x.isLoading)return <Loading/>;return <><PageHeader eyebrow="Mentorship" title="Assigned students" description="Review profiles, evidence, gap reports, and progress."/><StudentCards students={x.data?.students||[]}/></>}
export function StudentReview(){const {id}=useParams();const x=q(`mentor-${id}`,`/mentor/students/${id}`);const client=useQueryClient();const feedback=useMutation({mutationFn:(text:string)=>api.post(`/mentor/feedback/${id}`,{feedback:text}),onSuccess:()=>client.invalidateQueries({queryKey:[`mentor-${id}`]})});if(x.isLoading)return <Loading/>;const d=x.data;
 return <><PageHeader eyebrow="Student review" title={d.student?.name} description={`${d.profile?.branch||"Branch not set"} · ${d.student?.email}`}/><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><div className="card flex flex-col items-center"><ScoreRing value={d.report?.readinessScore||0}/><p className="mt-3 text-sm text-slate-500">{d.skills?.length||0} skills · {d.report?.evidenceCoverage||0}% evidence coverage</p></div><div className="card"><h2 className="text-lg font-bold">Priority gaps</h2><div className="mt-4 flex flex-wrap gap-2">{[...(d.report?.missingSkills||[]),...(d.report?.weakSkills||[])].slice(0,8).map((g:any)=><span className="pill bg-amber-50 text-amber-700">{g.skill} · {g.status}</span>)}</div><h3 className="mt-7 font-bold">Add mentor feedback</h3><textarea id="feedback" className="input mt-3 min-h-28" placeholder="Write specific, actionable feedback…"/><button className="btn-primary mt-3" onClick={()=>{const el=document.getElementById("feedback") as HTMLTextAreaElement;if(el.value)feedback.mutate(el.value)}}>Save feedback</button></div></div>{d.feedback?.length>0&&<div className="card mt-5"><h2 className="text-lg font-bold">Feedback history</h2>{d.feedback.map((f:any)=><div className="mt-3 rounded-xl bg-slate-50 p-4"><p className="text-sm">{f.feedback}</p><div className="mt-3 flex flex-wrap gap-2">{f.actionableSummary.map((a:string)=><span className="pill bg-blue-50 text-blue-700">{a}</span>)}</div></div>)}</div>}</>
}

export function PlacementDashboard(){return <PlacementAnalytics title="Placement command center"/>}
export function PlacementAnalytics({title="Institution analytics"}:{title?:string}){
 const {data,isLoading}=q("placement-analytics","/placement/analytics");if(isLoading)return <Loading/>;return <><PageHeader eyebrow="Cohort intelligence" title={title} description="A live view of student readiness across the institution." action={<a href={`${api.defaults.baseURL}/placement/export`} onClick={e=>{e.preventDefault();api.get("/placement/export",{responseType:"blob"}).then(r=>{const u=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=u;a.download="sgip-students.csv";a.click();URL.revokeObjectURL(u)})}} className="btn-secondary"><Download size={16}/>Export CSV</a>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total students" value={data.totalStudents} detail="Active student accounts" icon={Users}/><Stat label="Placement ready" value={data.placementReady} detail="Score of 75% or more" icon={CheckCircle2} tone="emerald"/><Stat label="Average readiness" value={`${data.averageReadiness}%`} detail="Across assessed students" icon={Gauge} tone="violet"/><Stat label="Branches tracked" value={data.branches?.length||0} detail="Academic cohorts" icon={BarChart3} tone="amber"/></div><div className="card mt-5"><h2 className="text-lg font-bold">Students by branch</h2><div className="mt-4 h-80"><ResponsiveContainer><BarChart data={data.branches}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#2563eb" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></>
}
export function PlacementStudents(){
 const {data,isLoading}=q("placement-students","/placement/students");if(isLoading)return <Loading/>;return <><PageHeader eyebrow="Talent directory" title="Student readiness list" description="Search, compare, and identify placement-ready candidates."/><div className="card overflow-hidden p-0"><div className="flex items-center gap-2 border-b p-4"><Search size={17} className="text-slate-400"/><input className="w-full outline-none" placeholder="Search students…"/></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Student</th><th>Branch</th><th>Target role</th><th>Readiness</th><th>Status</th></tr></thead><tbody className="divide-y">{data.students?.map((s:any)=><tr><td className="px-5 py-4"><b>{s.name}</b><p className="text-xs text-slate-400">{s.email}</p></td><td>{s.profile?.branch||"—"}</td><td>{s.profile?.targetRoleId?.title||"—"}</td><td className="font-bold">{s.report?.readinessScore??"—"}{s.report&&"%"}</td><td><span className={`pill ${s.report?.readinessScore>=75?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{s.report?.readinessScore>=75?"Ready":"Developing"}</span></td></tr>)}</tbody></table></div></div></>
}

export function AdminDashboard(){const users=q("admin-users","/admin/users");const roles=q("roles","/career-roles");if(users.isLoading||roles.isLoading)return <Loading/>;const u=users.data?.users||[];return <><PageHeader eyebrow="Administration" title="Platform control center" description="Manage access, career intelligence content, and governance."/><div className="grid gap-4 md:grid-cols-3"><Stat label="Platform users" value={users.data.total} detail="Across all roles" icon={Users}/><Stat label="Career roles" value={roles.data?.roles?.length||0} detail="Active role definitions" icon={BriefcaseBusiness} tone="violet"/><Stat label="Active accounts" value={u.filter((x:any)=>x.status==="active").length} detail="On this page" icon={ShieldCheck} tone="emerald"/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card"><h2 className="text-lg font-bold">User mix</h2><div className="mt-4 space-y-3">{["student","mentor","placement","admin"].map(role=><div className="flex justify-between rounded-xl bg-slate-50 p-3 capitalize"><span>{role}</span><b>{u.filter((x:any)=>x.role===role).length}</b></div>)}</div></div><div className="card"><h2 className="text-lg font-bold">System status</h2><div className="mt-5 space-y-4">{["Database connectivity","Deterministic scoring engine","Role-based authorization","Audit trail"].map(x=><div className="flex items-center justify-between"><span className="text-sm">{x}</span><span className="pill bg-emerald-50 text-emerald-700">Operational</span></div>)}</div></div></div></>}
export function AdminUsers(){const x=q("admin-users","/admin/users");const client=useQueryClient();const change=useMutation({mutationFn:({id,field,value}:any)=>api.patch(`/admin/users/${id}/${field}`,{[field]:value}),onSuccess:()=>client.invalidateQueries({queryKey:["admin-users"]})});if(x.isLoading)return <Loading/>;return <><PageHeader eyebrow="Access management" title="Users" description="Control roles and account status. Every change is audited."/><div className="card overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">User</th><th>Role</th><th>Status</th><th>Created</th></tr></thead><tbody className="divide-y">{x.data.users.map((u:any)=><tr><td className="px-5 py-4"><b>{u.name}</b><p className="text-xs text-slate-400">{u.email}</p></td><td><select className="input w-36" value={u.role} onChange={e=>change.mutate({id:u._id,field:"role",value:e.target.value})}>{["student","mentor","placement","admin"].map(r=><option>{r}</option>)}</select></td><td><select className="input w-32" value={u.status} onChange={e=>change.mutate({id:u._id,field:"status",value:e.target.value})}><option>active</option><option>suspended</option></select></td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></>}
export function AdminRoles(){const x=q("roles","/career-roles");if(x.isLoading)return <Loading/>;return <><PageHeader eyebrow="Career intelligence" title="Role definitions" description="Curated requirements power every explainable readiness score."/><div className="grid gap-4 md:grid-cols-2">{x.data.roles.map((r:any)=><div className="card"><div className="flex justify-between"><h2 className="text-lg font-bold">{r.title}</h2><span className="pill bg-blue-50 text-blue-700">{r.requiredSkills.length} skills</span></div><p className="mt-2 text-sm text-slate-500">{r.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{r.requiredSkills.slice(0,7).map((s:any)=><span className="pill bg-slate-50 text-slate-600">{s.skillName} · {s.weight}</span>)}</div></div>)}</div></>}
export function AuditLogs(){const x=q("audit","/admin/audit-logs");if(x.isLoading)return <Loading/>;return <><PageHeader eyebrow="Governance" title="Audit logs" description="Trace important identity, content, and configuration changes."/><div className="card">{x.data.logs?.length?x.data.logs.map((l:any)=><div className="flex gap-4 border-b py-4 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><FileText size={16}/></div><div><b className="text-sm">{l.action}</b><p className="text-xs text-slate-500">{l.entity} · {l.actorId?.name||"System"}</p><p className="mt-1 text-[11px] text-slate-400">{new Date(l.timestamp).toLocaleString()}</p></div></div>):<Empty title="No audit events" text="Important platform actions will appear here."/>}</div></>}
