import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Award, BookOpenCheck, BriefcaseBusiness, Check, CheckCircle2, Circle, Clock3, FileCheck2, Gauge, GitBranch, Lightbulb, Plus, Rocket, Sparkles, Target, Trash2, TrendingUp, Upload, UserRound, Zap } from "lucide-react";
import { useForm } from "react-hook-form";
import { Link } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../api";
import { Empty, ErrorText, Loading, NextLink, PageHeader, ScoreRing, Stat } from "../components";

const q=(key:string,url:string)=>useQuery({queryKey:[key],queryFn:()=>api.get(url).then(r=>r.data)});

export function StudentDashboard(){
  const {data,isLoading}=q("dashboard","/dashboard/student"); if(isLoading)return <Loading/>;
  const score=data?.report?.readinessScore||0, profile=data?.profile;
  return <><PageHeader eyebrow="Student workspace" title={`Good to see you, ${profile?.userId?.name||"future hire"}`} description="Here’s the clearest next move toward your target role."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Profile completion" value={`${profile?.profileCompletion||0}%`} detail="Complete profiles get sharper insights" icon={UserRound}/><Stat label="Readiness score" value={`${score}%`} detail={score>=75?"Placement-ready range":"Keep building evidence"} icon={Gauge} tone="emerald"/><Stat label="Skills tracked" value={data?.skillCount||0} detail={`${data?.evidenceCount||0} evidence items attached`} icon={Sparkles} tone="violet"/><Stat label="Roadmap progress" value={`${data?.roadmap?.progressPercentage||0}%`} detail="Tasks completed" icon={BookOpenCheck} tone="amber"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><div className="card"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Your placement trajectory</p><h2 className="mt-1 text-xl font-bold">{profile?.targetRoleId?.title||"Choose your target role"}</h2></div><NextLink to="/student/gap-analysis">View analysis</NextLink></div>
      <div className="mt-6 grid items-center gap-7 md:grid-cols-[160px_1fr]"><ScoreRing value={score}/><div><div className="mb-2 flex justify-between text-xs font-medium text-slate-500"><span>Current readiness</span><span>Placement-ready: 75%</span></div><div className="relative h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-emerald-500" style={{width:`${score}%`}}/><i className="absolute bottom-[-4px] left-[75%] h-5 w-px bg-slate-400"/></div><div className="mt-7 grid grid-cols-3 gap-3 text-center">{[["Matched",data?.report?.matchedSkills?.length||0,"text-emerald-600"],["Needs work",data?.report?.weakSkills?.length||0,"text-amber-600"],["Missing",data?.report?.missingSkills?.length||0,"text-rose-600"]].map(([l,v,c])=><div className="rounded-xl bg-slate-50 p-3" key={String(l)}><b className={`text-xl ${c}`}>{v}</b><p className="text-xs text-slate-500">{l}</p></div>)}</div></div></div>
    </div><div className="card bg-gradient-to-br from-[#122445] to-[#0c1830] text-white"><span className="pill bg-blue-400/15 text-blue-300"><Zap size={12}/> Recommended next action</span><h2 className="mt-5 text-2xl font-bold">{!profile?.targetRoleId?"Select a target career role":!data?.report?"Generate your first gap analysis":data?.roadmap?"Complete your next roadmap task":"Generate your personalized roadmap"}</h2><p className="mt-2 text-sm leading-6 text-slate-300">Your highest-leverage action is ready. It takes only a few minutes to create more clarity.</p><Link className="btn mt-6 bg-white text-slate-950 hover:bg-blue-50" to={!profile?.targetRoleId?"/student/roles":!data?.report?"/student/gap-analysis":data?.roadmap?"/student/roadmap":"/student/roadmap"}>Continue <Rocket size={16}/></Link></div></div>
  </>;
}

export function Profile(){
 const {data,isLoading}=q("profile","/student/profile");const client=useQueryClient();const {register,handleSubmit,reset}=useForm<any>({values:data?.profile||{}});
 const save=useMutation({mutationFn:(v:any)=>api.patch("/student/profile",v),onSuccess:r=>{client.invalidateQueries({queryKey:["profile"]});reset(r.data.profile)}});
 if(isLoading)return <Loading/>; const fields=[["phone","Phone"],["college","College / Institution"],["branch","Branch"],["year","Graduation year"],["cgpa","CGPA"],["location","Location"],["github","GitHub URL"],["linkedin","LinkedIn URL"],["portfolio","Portfolio URL"]];
 return <><PageHeader eyebrow="Profile" title="Your professional foundation" description="A complete, accurate profile improves role matching and institutional reporting."/><form onSubmit={handleSubmit(v=>save.mutate(v))} className="card"><div className="mb-7 flex items-center gap-5 border-b border-slate-100 pb-6"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 text-2xl font-bold text-white">YOU</div><div><h2 className="text-xl font-bold">Student profile</h2><p className="text-sm text-slate-500">{data?.profile?.profileCompletion||0}% profile complete</p><div className="mt-2 h-1.5 w-56 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${data?.profile?.profileCompletion||0}%`}}/></div></div></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{fields.map(([name,label])=><div key={name}><label className="label">{label}</label><input className="input" type={["year","cgpa"].includes(name)?"number":"text"} step={name==="cgpa"?"0.01":undefined} {...register(name)}/></div>)}<div className="md:col-span-2 xl:col-span-3"><label className="label">Career interests</label><input className="input" placeholder="Web development, AI, cloud…" {...register("careerInterests.0")}/></div><div className="md:col-span-2 xl:col-span-3"><label className="label">Short bio</label><textarea className="input min-h-28" {...register("bio")} placeholder="What are you learning, building, and aiming for?"/></div></div>{save.error&&<div className="mt-5"><ErrorText error={save.error}/></div>}<div className="mt-7 flex justify-end"><button className="btn-primary" disabled={save.isPending}><Check size={16}/>{save.isPending?"Saving…":"Save profile"}</button></div></form></>
}

export function Skills(){
 const {data,isLoading}=q("skills","/skills");const client=useQueryClient();const {register,handleSubmit,reset}=useForm<any>({defaultValues:{proficiency:"Beginner",category:"Technical"}});
 const add=useMutation({mutationFn:(v:any)=>api.post("/skills",v),onSuccess:()=>{client.invalidateQueries({queryKey:["skills"]});reset()}});
 const del=useMutation({mutationFn:(id:string)=>api.delete(`/skills/${id}`),onSuccess:()=>client.invalidateQueries({queryKey:["skills"]})});
 if(isLoading)return <Loading/>;return <><PageHeader eyebrow="Skills inventory" title="Show what you can do" description="Keep proficiency honest. Strong evidence raises confidence in your profile."/>
 <div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><form className="card h-fit" onSubmit={handleSubmit(v=>add.mutate(v))}><h2 className="text-lg font-bold">Add a skill</h2><div className="mt-5 space-y-4"><div><label className="label">Skill name</label><input required className="input" {...register("name")} placeholder="e.g. React"/></div><div><label className="label">Category</label><select className="input" {...register("category")}><option>Technical</option><option>Tool</option><option>Soft Skill</option><option>Domain</option></select></div><div><label className="label">Proficiency</label><select className="input" {...register("proficiency")}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div><label className="label">Years of experience</label><input className="input" type="number" step=".5" min="0" {...register("yearsOfExperience",{valueAsNumber:true})}/></div>{add.error&&<ErrorText error={add.error}/>}<button className="btn-primary w-full"><Plus size={16}/>Add skill</button></div></form>
 <div className="card"><div className="flex justify-between"><div><h2 className="text-lg font-bold">Your skills</h2><p className="text-sm text-slate-500">{data?.skills?.length||0} skills tracked</p></div></div><div className="mt-5 space-y-3">{data?.skills?.length?data.skills.map((s:any)=><div key={s._id} className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Sparkles size={18}/></div><div><b>{s.name}</b><p className="text-xs text-slate-500">{s.category} · {s.yearsOfExperience||0} years</p></div></div><div className="flex items-center gap-3"><span className={`pill ${s.proficiency==="Advanced"?"bg-emerald-50 text-emerald-700":s.proficiency==="Intermediate"?"bg-blue-50 text-blue-700":"bg-amber-50 text-amber-700"}`}>{s.proficiency}</span><button aria-label="Delete" onClick={()=>confirm("Delete this skill?")&&del.mutate(s._id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16}/></button></div></div>):<Empty title="No skills yet" text="Add your first skill to begin building your readiness profile."/>}</div></div></div></>
}

export function Evidence(){
 const skills=q("skills","/skills"), evidence=q("evidence","/skill-evidence");const client=useQueryClient();const {register,handleSubmit,reset}=useForm<any>({defaultValues:{evidenceType:"Project"}});
 const add=useMutation({mutationFn:(v:any)=>api.post("/skill-evidence",v),onSuccess:()=>{client.invalidateQueries({queryKey:["evidence"]});reset()}});
 if(skills.isLoading||evidence.isLoading)return <Loading/>;return <><PageHeader eyebrow="Proof of skill" title="Evidence makes skills credible" description="Attach projects, certificates, assessments, resume references, or GitHub work."/>
 <div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><form className="card h-fit" onSubmit={handleSubmit(v=>add.mutate(v))}><h2 className="text-lg font-bold">Add evidence</h2><div className="mt-5 space-y-4"><div><label className="label">Skill</label><select required className="input" {...register("skillId")}><option value="">Select skill</option>{skills.data?.skills?.map((s:any)=><option value={s._id}>{s.name}</option>)}</select></div><div><label className="label">Evidence type</label><select className="input" {...register("evidenceType")}>{["Project","Certificate","Assessment","Resume","GitHub"].map(x=><option>{x}</option>)}</select></div><div><label className="label">Title</label><input required className="input" {...register("title")} placeholder="What proves this skill?"/></div><div><label className="label">Link</label><input className="input" {...register("link")} placeholder="https://"/></div><div><label className="label">Description</label><textarea className="input min-h-24" {...register("description")}/></div>{add.error&&<ErrorText error={add.error}/>}<button className="btn-primary w-full"><FileCheck2 size={16}/>Save evidence</button></div></form>
 <div className="card"><h2 className="text-lg font-bold">Evidence library</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{evidence.data?.evidence?.length?evidence.data.evidence.map((e:any)=><div className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between"><span className="pill bg-indigo-50 text-indigo-700">{e.evidenceType}</span><span className={`pill ${e.status==="verified"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{e.status}</span></div><h3 className="mt-4 font-bold">{e.title}</h3><p className="mt-1 text-xs font-semibold text-blue-600">{e.skillId?.name}</p><p className="mt-2 line-clamp-2 text-sm text-slate-500">{e.description||"No description"}</p>{e.link&&<a className="mt-3 inline-block text-xs font-semibold text-blue-600" href={e.link} target="_blank">Open evidence →</a>}</div>):<div className="md:col-span-2"><Empty title="No evidence yet" text="Connect evidence to your skills to improve profile credibility."/></div>}</div></div></div></>
}

export function Roles(){
 const {data,isLoading}=q("roles","/career-roles");const client=useQueryClient();const choose=useMutation({mutationFn:(id:string)=>api.patch("/student/profile",{targetRoleId:id}),onSuccess:()=>client.invalidateQueries()});
 if(isLoading)return <Loading/>;return <><PageHeader eyebrow="Career role catalog" title="Choose a destination" description="Each role has transparent requirements, weights, and practical outcomes."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data?.roles?.map((role:any)=><div className="card group flex flex-col" key={role._id}><div className="flex justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><BriefcaseBusiness/></div><span className="pill h-fit bg-slate-100 text-slate-600">{role.category}</span></div><h2 className="mt-5 text-xl font-bold">{role.title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-500">{role.description}</p><div className="my-5 flex flex-wrap gap-1.5">{role.requiredSkills.slice(0,5).map((s:any)=><span className="pill bg-slate-50 text-slate-600">{s.skillName}</span>)}{role.requiredSkills.length>5&&<span className="pill bg-blue-50 text-blue-600">+{role.requiredSkills.length-5}</span>}</div><button onClick={()=>choose.mutate(role._id)} className="btn-secondary group-hover:border-blue-200 group-hover:text-blue-600"><Target size={16}/>Select role</button></div>)}</div></>
}

export function GapAnalysis(){
 const report=q("report","/gap-analysis/latest"),roles=q("roles","/career-roles");const client=useQueryClient();const {register,handleSubmit}=useForm<any>();const generate=useMutation({mutationFn:(v:any)=>api.post("/gap-analysis/generate",v),onSuccess:()=>client.invalidateQueries({queryKey:["report"]})});
 if(report.isLoading||roles.isLoading)return <Loading/>;const r=report.data?.report;const chart=r?.skillBreakdown?.map((x:any)=>({name:x.skill.length>9?x.skill.slice(0,8)+"…":x.skill,score:x.score}))||[];
 return <><PageHeader eyebrow="Explainable scoring" title="Skill gap analysis" description="Weighted role requirements meet your declared proficiency and supporting evidence." action={<form className="flex gap-2" onSubmit={handleSubmit(v=>generate.mutate(v))}><select className="input min-w-48" {...register("roleId")}><option value="">Current target role</option>{roles.data?.roles?.map((x:any)=><option value={x._id}>{x.title}</option>)}</select><button className="btn-primary" disabled={generate.isPending}><Target size={16}/>{generate.isPending?"Analyzing…":"Run analysis"}</button></form>}/>
 {generate.error&&<div className="mb-4"><ErrorText error={generate.error}/></div>}{!r?<Empty title="No gap report yet" text="Select a role and run your first deterministic readiness analysis."/>:<><div className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div className="card flex flex-col items-center justify-center text-center"><ScoreRing value={r.readinessScore} size={160}/><h2 className="mt-4 text-xl font-bold">{r.roleId?.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{r.explanation}</p><div className="mt-5 w-full rounded-xl bg-blue-50 p-3 text-sm text-blue-700"><b>{r.evidenceCoverage}%</b> evidence coverage</div></div><div className="card"><h2 className="text-lg font-bold">Skill coverage</h2><div className="mt-4 h-72"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis domain={[0,100]} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="score" radius={[5,5,0,0]}>{chart.map((x:any)=><Cell fill={x.score>=70?"#10b981":x.score>0?"#f59e0b":"#f43f5e"}/>)}</Bar></BarChart></ResponsiveContainer></div></div></div>
 <div className="mt-5 card overflow-hidden p-0"><div className="border-b p-5"><h2 className="text-lg font-bold">Skill-by-skill breakdown</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Skill</th><th>Required</th><th>Current</th><th>Weight</th><th>Status</th></tr></thead><tbody className="divide-y">{r.skillBreakdown.map((x:any)=><tr><td className="px-5 py-4 font-semibold">{x.skill}</td><td>{x.requiredLevel}</td><td>{x.currentLevel}</td><td>{x.weight}</td><td><span className={`pill ${x.status==="matched"?"bg-emerald-50 text-emerald-700":x.status==="weak"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700"}`}>{x.status}</span></td></tr>)}</tbody></table></div></div></>}</>
}

export function RoadmapPage(){
 const {data,isLoading}=q("roadmap","/roadmap");const client=useQueryClient();const generate=useMutation({mutationFn:()=>api.post("/roadmap/generate"),onSuccess:()=>client.invalidateQueries({queryKey:["roadmap"]})});const update=useMutation({mutationFn:({id,status}:any)=>api.patch(`/roadmap/task/${id}`,{status}),onSuccess:()=>client.invalidateQueries({queryKey:["roadmap"]})});
 if(isLoading)return <Loading/>;const road=data?.roadmap;return <><PageHeader eyebrow="Personalized plan" title="Your route to readiness" description="Progress through focused phases—from foundations to placement confidence." action={<button className="btn-primary" onClick={()=>generate.mutate()}><Sparkles size={16}/>{road?"Regenerate roadmap":"Generate roadmap"}</button>}/>{generate.error&&<ErrorText error={generate.error}/>}
 {!road?<div className="mt-4"><Empty title="Your roadmap is waiting" text="Generate a gap analysis first, then create a prioritized learning journey."/></div>:<><div className="card mb-5"><div className="flex justify-between text-sm"><b>Overall roadmap progress</b><span className="font-semibold text-blue-600">{road.progressPercentage}%</span></div><div className="mt-3 h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-emerald-500" style={{width:`${road.progressPercentage}%`}}/></div></div><div className="space-y-5">{road.phases.map((phase:any,index:number)=><div className="card" key={phase._id}><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#0d1b35] font-bold text-white">{index+1}</div><div className="flex-1"><h2 className="text-lg font-bold">{phase.name}</h2><p className="mt-1 text-sm text-slate-500">{phase.description}</p><div className="mt-5 space-y-3">{phase.tasks.length?phase.tasks.map((task:any)=><button onClick={()=>update.mutate({id:task._id,status:task.status==="Completed"?"Not Started":"Completed"})} className="flex w-full items-start gap-3 rounded-xl border border-slate-100 p-4 text-left hover:border-blue-200" key={task._id}>{task.status==="Completed"?<CheckCircle2 className="mt-0.5 text-emerald-500" size={20}/>:<Circle className="mt-0.5 text-slate-300" size={20}/>}<div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><b className={task.status==="Completed"?"text-slate-400 line-through":""}>{task.title}</b><span className="pill bg-blue-50 text-blue-700">{task.priority}</span></div><p className="mt-1 text-xs text-slate-500">{task.description}</p><p className="mt-2 flex items-center gap-1 text-xs font-semibold text-slate-400"><Clock3 size={13}/>{task.estimatedHours} hours · {task.skill}</p></div></button>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">This phase unlocks as more gaps are identified.</p>}</div></div></div></div>)}</div></>}</>
}

export function Reports(){
 const {data,isLoading}=q("report","/gap-analysis/latest");if(isLoading)return <Loading/>;const r=data?.report;if(!r)return <Empty title="Nothing to report yet" text="Generate a skill gap analysis to create your readiness report." action={<Link to="/student/gap-analysis" className="btn-primary">Run analysis</Link>}/>;
 const pie=[{name:"Matched",value:r.matchedSkills.length,color:"#10b981"},{name:"Weak",value:r.weakSkills.length,color:"#f59e0b"},{name:"Missing",value:r.missingSkills.length,color:"#f43f5e"}];return <><PageHeader eyebrow="Readiness report" title="Your career intelligence summary" description={`Generated for ${r.roleId?.title}. Print this page to save it as a PDF.`} action={<button className="btn-secondary" onClick={()=>window.print()}><Upload className="rotate-180" size={16}/>Export PDF</button>}/><div className="grid gap-5 lg:grid-cols-3"><div className="card flex items-center justify-center"><ScoreRing value={r.readinessScore}/></div><div className="card lg:col-span-2"><h2 className="text-lg font-bold">Coverage composition</h2><div className="grid items-center md:grid-cols-2"><div className="h-56"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" innerRadius={55} outerRadius={85} paddingAngle={3}>{pie.map(x=><Cell fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="space-y-3">{pie.map(x=><div className="flex justify-between rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{background:x.color}}/>{x.name}</span><b>{x.value}</b></div>)}</div></div></div></div><div className="card mt-5"><h2 className="text-lg font-bold">Priority recommendations</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.recommendations.map((x:string,i:number)=><div className="flex gap-3 rounded-xl border border-slate-100 p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-blue-50 text-xs font-bold text-blue-600">{i+1}</span><span className="text-sm">{x}</span></div>)}</div></div></>
}
